### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by fionalluo** [facebookresearch/modemv2#1]
Hi, upon running the training script in the readme through
`sh scripts/franka/bin_pick/modemv2.sh`

I receive an `OSError: [Errno 12] Cannot allocate memory`, despite having sufficient available memory (240G RAM and 2G swap). This error occurs when loading at least 1 demo. Reducing batch size and other variables in the sh file does not help either. Has anyone encountered this issue? 

I saw in the Readme we need 80gb to run modemv2. Is that 80GB on a GPU alone?

The full stack trace is below:

```
Error executing job with overrides: ['task=franka-FrankaBinPick_v2d', 'exp_name=bin_pick_modemv2', 'iterations=1', 'discount=0.95', 'train_steps=200000', 'seed=1', 'demos=10', 'img_size=224', 'lr=3e-4', 'batch_size=256', 'episode_length=100', 'camera_views=[left_cam,right_cam]', 'left_crops=[0,0]', 'top_crops=[0,0]', 'action_repeat=1', 'seed_steps=5000', 'eval_episodes=30', 'plan_policy=true', 'bc_rollout=true', 'bc_q_pol=true', 'ensemble_size=6', 'val_min_w=0.0', 'val_mean_w=1.0', 'val_std_w=-10.00', 'mix_schedule="linear(0.0,1.0,5000,105000)"', 'mixture_coef=1.0', 'save_freq=2500', 'eval_freq=2500', 'min_std=0.1', 'uncertainty_weighting=false']
Traceback (most recent call last):
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 133, in setup
    self._wl = wandb_setup.setup()
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 318, in setup
    ret = _setup(settings=settings)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 313, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 299, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 107, in __init__
    self._settings = self._settings_setup(settings, self._early_logger)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 136, in _settings_setup
    s._infer_run_settings_from_environment(_logger=early_logger)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 1394, in _infer_run_settings_from_environment
    program_relpath = self.program_relpath or _get_program_relpath_from_gitrepo(
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_settings.py", line 138, in _get_program_relpath_from_gitrepo
    root = repo.root
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/lib/git.py", line 46, in root
    return self.repo.git.rev_parse("--show-toplevel")
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/git/cmd.py", line 986, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/git/cmd.py", line 1598, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/git/cmd.py", line 1262, in execute
    proc = safer_popen(
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/subprocess.py", line 1752, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
OSError: [Errno 12] Cannot allocate memory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/harsh/fiona/modemv2/modemv2/train.py", line 500, in <module>
    train()
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/harsh/fiona/modemv2/modemv2/train.py", line 236, in train
    L = logger.Logger(work_dir, cfg)
  File "/home/harsh/fiona/modemv2/modemv2/logger.py", line 395, in __init__
    wandb.init(
  File "/home/harsh/miniconda3/envs/modemv2/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1037, in init
    raise Exception("problem") from error_seen
Exception: problem
```

**Comment by fionalluo** [comment]
Resolved by decreasing train_steps, since the replay buffer size is large and depends on train_steps
